### ISSUE TITLE
Doesn't work on Node v0.10.x

### ISSUE THREAD

**Issue by dfellis** [parro-it/canibekikked#4]
```
$ canibekiked dfellis

/Users/damocles/.nvm/v0.10.31/lib/node_modules/canibekiked/cli.js:3
const ora = require('ora');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

README should state what versions of Node are supported.

**Comment by parro-it** [comment]
Thank you, I added a note on readme
